openapi: 3.0.0

info:
  title: CollabTrack Backend API
  description: REST API documentation for CollabTrack platform
  version: 1.0.0

servers:
  - url: https://collabtrack-api.onrender.com
    description: Production
  - url: http://localhost:9000
    description: Local

tags:
  - name: Health
  - name: Auth
  - name: Users

paths:
  /api/v1/healthcheck:
    get:
      tags:
        - Health
      summary: Health check API
      responses:
        "200":
          description: Server is running

  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@gmail.com
                password:
                  type: string
                  example: password123
      responses:
        "200":
          description: Login successful
